variables:
  PROJECT_CODE: p10000
  PROJECT_NAME: cms
  PROJECT_VERSION: 0.0.1
  TEST_HOST: test.dayukeji.xin
  DEV_HOST: tst.dayukeji.xin
  PROD_HOST: api.dayukeji.xin

stages:
 - depo

cache:
 paths:
   - node_modules

depo-dev:
 only:
   - /^dev-\d+\.\d+\.\d+$/
 script:
   - npm i && npm run clean
   - npm run dev
   - ssh depo@${DEV_HOST} 'mv /var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}{,~} || echo "no such directory."'
   - scp -r build/. depo@${DEV_HOST}:/var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}/
   - ssh depo@${DEV_HOST} 'rm -rf /var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}~'
 stage: depo
 tags:
   - node

depo-test:
 only:
   - /^test-\d+\.\d+\.\d+$/
 script:
   - npm i && npm run clean
   - npm run test
   - ssh depo@${TEST_HOST} 'mv /var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}{,~} || echo "no such directory."'
   - scp -r build/. depo@${TEST_HOST}:/var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}/
   - ssh depo@${TEST_HOST} 'rm -rf /var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}~'
 stage: depo
 tags:
   - node

depo-prod:
 only:
   - /^v-\d+\.\d+\.\d+$/
 script:
   - npm i && npm run clean
   - npm run prod
   - ssh depo@${PROD_HOST} 'mv /var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}{,~} || echo "no such directory."'
   - scp -r build/. depo@${PROD_HOST}:/var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}/
   - ssh depo@${PROD_HOST} 'rm -rf /var/www/hosts/${PROJECT_CODE}.${PROJECT_NAME}~'
 stage: depo
 tags:
   - node
